# Bulgarian# bg.toml - v10.2.40.2
[addon]
appDesc = '''Сваляне на видео от мрежата'''
restore_purchase_button = '''Възстановяване на покупката'''
get_premium_button = '''Вземи премиум достъп'''
back = '''Назад'''
rm_notifications_all = '''Премахни всички уведомления'''
waiting_for_media = '''Изчакване за медия'''
nomedia_title = '''Не виждате медията която търсете?'''
nomedia_description = '''Стартирайте видеото (и пропуснете рекламите, ако има такива), за да помогнете за откриването на медията. Или съобщете за липсваща медия.'''
nomedia_reload_button = '''Принудително засичане'''
nomedia_reload_button_tooltip = '''Принудително презареждане на страницата'''
show_nomedia_button = '''Няма видео'''
show_nomedia_button_tooltip = '''Кликни тук ако не намираш видео'''
setting_button_tooltip = '''Настройки'''
history_button_tooltip = '''Покажи история на сваляне'''
show_all_history_button = '''Покажи всички'''
complete_title = '''Завършено'''
hide_complete_button = '''Скрий'''
translate_button_tooltip = '''Помогнете за превода на VDH'''
help_button_tooltip = '''Помощ'''
open_source_tab_button_tooltip = '''Отвори основен раздел'''
retry_download_button_tooltip = '''Свали отново'''
delete_file_button_tooltip = '''Изтрий файл'''
download_directory_button_tooltip = '''Покажи папката за изтегляне'''
clear_downloaded_tooltip = '''Изчисти напълно свалените'''
show_in_popup_button_tooltip = '''Покажи в изскачащ прозорец'''
show_in_sidebar_button_tooltip = '''Покажи в страничната лента'''
video_not_playing_button_tooltip = '''Видеото не се стартира?'''
play = '''Пусни'''
warn_drm_tooltip = '''Засечен DRM'''
version_title = '''Версия'''
account_title = '''Профил'''
one_hundred_downloads_title = '''Вие свалихте 100 видеа'''
leave_review_description = '''Надяваме се, че ви харесва VDH :) Бихте ли написали хубаво ревю за уебсайта на добавката?'''
leave_review_button = '''Оставете оценка'''
account_status = '''Статус'''
account_status_premium = '''Премиум ($1)'''
free_account = '''Безплатен план'''
copy_to_clipboard = '''Копирай информацията в клипборда'''
my_account_button = '''Моят профил'''
download_title = '''Свалени'''
show_notification = '''Покажи уведомление след сваляне'''
max_parallel_downloads = '''Максимален брой едновременни изтегляния'''
saveas_detected_warning = '''Установихме, че браузърът ви показва диалогов прозорец „Запазване като“, след като изтеглянето приключи. Препоръчваме ви да деактивирате тази опция в настройките на браузъра си.'''
change_saveas_setting = '''Промени настройки'''
download_directory_title = '''Директория на сваляне'''
download_directory_description = '''Видеоклиповете се изтеглят в директорията за изтегляне на браузъра по подразбиране. Можете също да укажете поддиректория. Директориите за изтегляне, специфични за уебсайта, могат да бъдат зададени с инструмента за интелигентно именуване.'''
change_browser_download_directory = '''Промяна на директорията за изтегляне на браузъра'''
bad_download_subdirectory_warning = '''Посочената от вас поддиректория е невалидна.'''
download_subdirectory = '''Поддиректория за сваляне'''
private_browsing_title = '''Частно сърфиране'''
private_browsing_warning = '''VDH не е активиран в частен/инкогнито прозорец. Трябва да включите тази опция ръчно (това не е задължително).'''
private_browsing_notifications = '''Покажи уведомление за частни изтегляния'''
private_browsing_button = '''Промени настройки на частно сърфиране'''
prefer_original_audio = '''Предпочитам оригинално аудио'''
settings_history_title = '''История'''
transient_history_description = '''Покажи завършените сваляния в панела'''
history_limit = '''Забравете историята на изтеглянията след X дни'''
appearance_title = '''Външен вид'''
theme_title = '''Тема'''
theme_light = '''Светло'''
theme_dark = '''Тъмно'''
theme_system = '''Система'''
popup_size_title = '''Размер на прозореца'''
popup_size_small = '''Малък'''
popup_size_medium = '''Среден'''
popup_size_big = '''Голям'''
font_size_title = '''Размер на текста'''
font_size_default = '''Подразбиране'''
font_size_large = '''Уголемен'''
font_size_verylarge = '''Много уголемен'''
panel_position_title = '''Позиция на панела'''
use_popup = '''Покажи в изскачащо известие'''
use_sidebar = '''Покажи в страничната лента'''
behavior_title = '''Поведение'''
controls_title = '''Контроли'''
show_in_context_menu = '''Достъп до команди чрез щракване с десния бутон на мишката върху страницата'''
restart_addon = '''Презареди добавката'''
reset_settings = '''Нулиране на настройките'''
prefered_quality = '''Предпочитано качество на видео'''
prefered_quality_highest = '''Най-високо (бавно изтегляне, висока резолюция)'''
prefered_quality_1080p = '''1080p (добро по подразбиране)'''
prefered_quality_720p = '''720p (бързо изтегляне, ниска резолюция)'''
prefered_quality_480p = '''480p (по-бързо изтегляне, по-ниска резолюция)'''
prefer_mkv = '''Свали като MKV ако е възможно'''
preview_mode_title = '''Преглед на медийното съдържание'''
preview_mode_none = '''Неспособен'''
preview_mode_video = '''Кратко преглеждане на видеото'''
preview_mode_image = '''Изображение'''
media_discovered_ordering_title = '''Стратегия за сортиране на медии'''
order_media_smart = '''Умно (Препоръчително)'''
order_media_by_newest = '''Първо новите'''
order_media_by_oldest = '''Първо старите'''
history_title = '''История на изтеглянията'''
history_warning = '''Ние не записваме историята на изтеглянията ви. Искате ли VDH да запомни историята на изтеглянията ви?'''
history_warning_2 = '''Не се притеснявайте, всичко остава на вашата машина. Ние ценим вашата поверителност.'''
enable_history = '''Позволи история'''
clear_history = '''Изчисти история'''
disable_history = '''Не запомняй моята история'''
no_downloads_yet = '''Все още няма записи.'''
download_failed = '''Свалянето се провали'''
download_failed_description = '''За съжаление не успяхме да изтеглим този конкретен медиен файл. Стараем се да поддържаме колкото се може повече уебсайтове, така че ще ни помогне много, ако можете да съобщите за тази грешка (анонимно е!).'''
download_interrupted = '''Свалянето е прекъснато'''
download_interrupted_description = '''Успяхме да изтеглим файла ви, но имаше проблеми с мрежата, така че файлът може да е по-кратък от очакваното. Стараем се да поддържаме колкото се може повече уебсайтове, така че ще ни помогне много, ако можете да съобщите за този проблем (анонимно е!).'''
download_with_drm_failed_description = '''Нещо не сработи. И смятаме, че това видео има DRM. Не поддържаме видеоклипове с DRM.'''
no_youtube = '''Сваляния от Ютюб не са позволени'''
no_youtube_description = '''За съжаление, уеб магазинът на Хром не позволява разширения за изтегляне на видеоклипове от Ютюб, така че не успяхме да включим тази функция във версията на разширението за Хром.'''
no_youtube_description_2 = '''Моля, използвайте Файърфокс или Майкрософт Едж'''
premium_required = '''Нужен е премиум достъп'''
premium_yt_required_description = '''Без Премиум достъп, изтегляне от Ютюб може да се извърши само 2 часа след предишното.'''
premium_hls_required_description = '''Без Премиум достъп, изтегляне на HLS или MPD може да се извърши само 2 часа след предишното.'''
premium_all_required_description = '''Без Премиум достъп, изтеглянето може да се извърши само 2 часа след предишното'''
youtube_too_many_downloads = '''Опа, изглежда Ютюб е блокиран'''
youtube_too_many_downloads_description = '''Понякога Ютюб ограничава броя на заявените видеоклипове. За съжаление не можем да направим нищо по въпроса. Опитайте отново по-късно.'''
stop = '''Стоп'''
cancel = '''Отмяна'''
copy_url = '''Копирай URL адрес'''
always_copy_url = '''Винаги копирай URL'''
download_button = '''Сваляне'''
download_as_button_and_menu = '''Свали като...'''
rename_short = '''Преименувай'''
always_download_as_menu = '''Винаги сваляй като...'''
download_audio_button = '''Аудио'''
download_audio_and_video_menu = '''Свали Аудио и Видео'''
download_audio_only_menu = '''Свали Аудио'''
audio_only_for_this_website = '''Винаги само Аудио от този сайт'''
details = '''Детайли'''
report = '''Доклад'''
reporting = '''Докладване...'''
reported_thankyou = '''Благодарим Ви!'''

[web]
back = '''Назад'''
header_help = '''Помощ'''
header_ask_question = '''Задайте ни въпрос'''
activate_title = '''Активация'''
activate_pending = '''Изчакване...'''
activate_success = '''Успешно'''
activate_error = '''Грешка'''
activate_no_addon_found = '''Не е намерена добавка. Добавката инсталирана ли е?'''
activate_no_method_found = '''Не е намерен метод.'''
activate_help_me = '''Помогни ми.'''
issue_title = '''Възстановяване на покупката'''
issue_submit = '''Предоставям'''
issue_thank_you = '''Благодаря'''
issue_enter_email = '''За да възстановите покупката си, въведете имейл адреса, който сте използвали за закупуване на лиценза си:'''
issue_email_sent = '''Току-що ви изпратихме имейл с линк, който ще активира вашия продукт.'''
issue_or_digit = '''Или можете да въведете 6-цифрения код, който ви изпратихме:'''
issue_just_digit = '''Въведете 6-цифрения код, който ви изпратихме:'''
issue_i_have_a_code = '''(Кликнете тук, ако вече имате код)'''
issue_i_have_a_key = '''(Кликнете тук, ако имате лицензионен ключ)'''
issue_key = '''Въведете вашия лицензионен ключ за VDH:'''
landing_text1 = '''Изтеглете всяко видео от всякакви уебсайтове, просто работи!'''
landing_text2 = '''1000+ поддържани уебсайтове'''
landing_text3 = '''Доверен от 7 милиона потребители'''
landing_text4 = '''4,5 звезди рейтинг в магазина за добавки'''
landing_install_for_google = '''Инсталиране за Хром'''
landing_install_for_mozilla = '''Инсталиране за Файърфокс'''
landing_install_for_microsoft = '''Инсталиране за Едж'''
landing_feature1_title = '''HD изтегляне с пълна скорост'''
landing_feature1_description = '''Изтегляйте видеоклипове с висока разделителна способност, с максимална скорост. Гордеем се да заявим, че разполагаме с най-бързата система за изтегляне.'''
landing_feature2_title = '''Архивирай видеа'''
landing_feature2_description = '''Архивирайте любимите си видеоклипове, като се уверите, че нищо не е забравено.'''
landing_feature3_title = '''Поддръжка на живо поточно предаване'''
landing_feature3_description = '''Насладете се на гледане на предавания на живо офлайн, освобождавайки ви от ограниченията в реално време.'''
landing_feature4_title = '''Изтегляне на Аудио'''
landing_feature4_description = '''Извличайте аудио от видеоклипове, конвертирайки ги в MP3 файлове или подкасти за лесно слушане.'''
premium_hero1 = '''Платете веднъж, използвайте завинаги'''
premium_hero2 = '''Вземете доживотен лиценз за VDH'''
premium_hero3 = '''Изтегляйте всякакви видеоклипове, колкото искате, без ограничения.'''
premium_supported_payment_methods = '''Поддържани методи за плащане'''
premium_buy = '''Купи'''
welcome_text = '''Сега няма да пропуснете нито едно видео!'''
welcome_pin_message = '''Закачете иконата на добавката към лентата с инструменти:'''


[addon]

# Video DownloadHelper description. 132 characters max.
appDesc = "Download Videos from the Web."
