# sk.toml - v10.5.2.2
[addon]
appDesc = '''Sťahovanie videí z webu.'''
restore_purchase_button = '''Obnoviť nákup'''
get_premium_button = '''Získajte Prémium'''
get_premium_description_button = '''Sťahovanie bez obmedzení'''
back = '''Späť'''
rm_notifications_all = '''Zastaviť všetky oznámenia'''
waiting_for_media = '''Čakanie na médiá...'''
nomedia_title = '''Nevidíte médiá, ktoré hľadáte?'''
nomedia_description = '''Angličtina: Spustite video (a preskočte reklamy, ak sú nejaké), aby ste pomohli rozpoznať médiá. Alebo nahláste chýbajúce médiá.'''
nomedia_reload_button = '''Silná detekcia'''
nomedia_reload_button_tooltip = '''Vynútiť znovu načítať podstránky (vymazať súbory cookie)'''
show_nomedia_button = '''Žiadne video?'''
show_nomedia_button_tooltip = '''Ak nemôžete nájsť svoje video, kliknite sem'''
setting_button_tooltip = '''Nastavenia'''
history_button_tooltip = '''Zobraziť históriu sťahovania'''
show_all_history_button = '''zobraziť všetky'''
complete_title = '''Dokončené'''
hide_complete_button = '''skryť'''
translate_button_tooltip = '''Pomôžte preložiť VDH'''
help_button_tooltip = '''Pomoc'''
open_source_tab_button_tooltip = '''Otvoriť kartu zdroja'''
retry_download_button_tooltip = '''Zopakovať stiahnutie'''
delete_file_button_tooltip = '''Odstrániť súbor'''
download_directory_button_tooltip = '''Zobraziť priečinok na stiahnutie'''
clear_downloaded_tooltip = '''Vymazať dokončené stiahnuté'''
show_in_popup_button_tooltip = '''Zobraziť vo vyskakovacom okne'''
show_in_sidebar_button_tooltip = '''Zobraziť na bočnom paneli'''
video_not_playing_button_tooltip = '''Video sa neprehráva?'''
play = '''Prehrať'''
warn_drm_tooltip = '''Bolo zistené DRM'''
version_title = '''Verzia'''
account_title = '''Účet'''
one_hundred_downloads_title = '''Stiahli ste si 100 videí!'''
leave_review_description = '''Dúfame, že sa vám Pomocník na sťahovanie videa páči :) Nevadilo by vám napísať peknú recenziu na webovú stránku doplnku?'''
leave_review_button = '''Napíšte recenziu'''
account_status = '''Stav'''
account_status_premium = '''Prémium (1 USD)'''
free_account = '''Zadarmo plán'''
copy_to_clipboard = '''Skopírujte informácie do schránky'''
my_account_button = '''Môj účet'''
download_title = '''Stiahnuté'''
show_notification = '''Po dokončení sťahovania zobraziť upozornenie'''
max_parallel_downloads = '''Maximálny počet súbežných sťahovaní'''
saveas_detected_warning = '''Zistili sme, že váš prehliadač po dokončení sťahovania zobrazuje dialógové okno „Uložiť ako“. Odporúčame túto možnosť vypnúť v nastaveniach prehliadača'''
change_saveas_setting = '''Zmeniť nastavenie'''
download_directory_title = '''Adresár so Stiahnutými súbormi'''
download_directory_description = '''Videá sa sťahujú do predvoleného adresára na stiahnutie prehliadača. Môžete tiež zadať podadresár. Adresáre sťahovania špecifické pre webové stránky je možné nastaviť pomocou nástroja smartnaming.'''
change_browser_download_directory = '''Zmeňte adresár na stiahnutie z prehliadača'''
bad_download_subdirectory_warning = '''Zadaný podadresár nie je platný.'''
download_subdirectory = '''Stiahnuť podadresár'''
private_browsing_title = '''Súkromné ​​prehliadanie'''
private_browsing_warning = '''Pomocník na sťahovanie videa nie je povolený v súkromných oknách alebo oknách inkognito. Túto možnosť musíte zapnúť manuálne (nie je to potrebné).'''
private_browsing_notifications = '''Zobraziť upozornenie na súkromné ​​sťahovanie'''
private_browsing_button = '''Zmeňte nastavenie súkromného prehliadania'''
throttle_youtube = '''Obmedzte YouTube (pomalšie sťahovanie, ale menej pravdepodobné, že bude zablokovaný)'''
prefer_original_audio = '''Uprednostňujte originálny zvuk'''
settings_history_title = '''História'''
transient_history_description = '''Zobraziť kompletné stiahnuté súbory na paneli'''
history_limit = '''Zabudnite na históriu sťahovania po X dňoch'''
appearance_title = '''Vzhľad'''
theme_title = '''Téma'''
theme_light = '''svetlá'''
theme_dark = '''tmavá'''
theme_system = '''systém'''
popup_size_title = '''Veľkosť okna'''
popup_size_small = '''Malý'''
popup_size_medium = '''Stredná'''
popup_size_big = '''Veľký'''
font_size_title = '''Veľkosť textu'''
font_size_default = '''Predvolené'''
font_size_large = '''Veľký'''
font_size_verylarge = '''Veľmi veľké'''
panel_position_title = '''Poloha panelu'''
use_popup = '''Zobraziť vo vyskakovacom okne'''
use_sidebar = '''Zobraziť na bočnom paneli'''
behavior_title = '''Správanie'''
controls_title = '''Ovládacie prvky'''
show_in_context_menu = '''Prístup k príkazom získate kliknutím pravým tlačidlom myši na stránku'''
restart_addon = '''Znova načítať doplnok'''
reset_settings = '''Obnoviť nastavenia'''
preferred_quality = '''Preferovaná kvalita videa'''
preferred_quality_highest = '''Najvyššie (pomalé sťahovanie, vysoké rozlíšenie)'''
preferred_quality_1080p = '''1080p (dobré predvolené nastavenie)'''
preferred_quality_720p = '''720p (rýchle sťahovanie, nízke rozlíšenie)'''
preferred_quality_480p = '''480p (rýchlejšie sťahovanie, nižšie rozlíšenie)'''
prefer_mkv = '''Stiahnite si ako MKV, ak je to možné'''
preview_mode_title = '''Ukážka médií'''
preview_mode_none = '''Zakázané'''
preview_mode_video = '''Krátky náhľad videa'''
preview_mode_image = '''Obrázok'''
media_discovered_ordering_title = '''Stratégia triedenia médií'''
order_media_smart = '''Inteligentné (odporúčané)'''
order_media_by_newest = '''Najnovšie ako prvé'''
order_media_by_oldest = '''Najstaršie ako prvé'''
settings_subtitles_title = '''Preferované jazyky titulkov'''
settings_audio_tracks_title = '''Preferované zvukové stopy'''
history_title = '''História sťahovania'''
history_warning = '''Nezaznamenávame vašu históriu sťahovania. Chcete, aby si Pomocník na sťahovanie videa zapamätal vašu históriu sťahovania?'''
history_warning_2 = '''Nebojte sa, všetko zostane na vašom stroji. Ceníme si vaše súkromie.'''
enable_history = '''Povoliť históriu'''
clear_history = '''Vymazať históriu'''
disable_history = '''Nepamätaj si moju históriu'''
no_downloads_yet = '''Zatiaľ žiadne záznamy.'''
download_failed = '''Sťahovanie zlyhalo'''
download_failed_description = '''Bohužiaľ sa nám nepodarilo stiahnuť toto konkrétne médium. Snažíme sa podporovať čo najviac webových stránok, takže by nám veľmi pomohlo, keby ste túto chybu nahlásili (je to anonymné!).'''
download_interrupted = '''Sťahovanie bolo prerušené'''
download_interrupted_description = '''Podarilo sa nám stiahnuť váš súbor, ale vyskytli sa problémy so sieťou, takže súbor môže byť kratší, ako sa očakávalo. Snažíme sa podporovať čo najviac webových stránok, preto by nám veľmi pomohlo, keby ste tento problém nahlásili (je to anonymné!).'''
download_with_drm_failed_description = '''Niečo nefungovalo. A myslíme si, že toto video má DRM. Videá s DRM nepodporujeme.'''
no_youtube = '''Sťahovanie z youtube nie je povolené'''
no_youtube_description = '''Internetový obchod Chrome bohužiaľ nepovoľuje rozšírenia na sťahovanie videí YouTube, takže túto funkciu sme nemohli zahrnúť do verzie rozšírenia pre Chrome.'''
no_youtube_description_2 = '''Použite Firefox alebo Microsoft Edge'''
premium_required = '''Vyžaduje sa prémium verzia'''
premium_yt_required_description = '''Bez stavu Premium je možné sťahovanie YouTube vykonať iba 2 hodiny po predchádzajúcom.'''
premium_hls_required_description = '''Bez stavu Premium je možné sťahovanie HLS alebo MPD vykonať iba 2 hodiny po predchádzajúcom.'''
premium_all_required_description = '''Bez stavu Premium je možné sťahovanie vykonať iba 2 hodiny po predchádzajúcom.'''
youtube_too_many_downloads = '''Hops, zdá sa, že YouTube je zablokovaný'''
youtube_too_many_downloads_description = '''YouTube niekedy obmedzí počet požadovaných videí. Bohužiaľ s tým nemôžeme nič robiť. Skúste to znova neskôr.'''
stop = '''Stop'''
cancel = '''Zrušiť'''
copy_url = '''Kopírovať URL'''
always_copy_url = '''Vždy skopírujte URL'''
download_button = '''Stiahnuť'''
download_as_button_and_menu = '''Stiahnuť ako…'''
rename_short = '''Premenovať'''
always_download_as_menu = '''Vždy stiahnuť ako…'''
download_audio_button = '''Zvuk'''
download_audio_and_video_menu = '''Stiahnite si zvuk a video'''
download_audio_only_menu = '''Stiahnite si zvuk'''
audio_only_for_this_website = '''Vždy zvuk len pre túto webovú stránku'''
details = '''Podrobnosti'''
report = '''Správa'''
reporting = '''Nahlasuje sa…'''
reported_thankyou = '''Ďakujem!'''
move_lang_up = '''Posunúť sa hore'''
move_lang_down = '''Presuňte sa nadol'''
remove_lang = '''Odstrániť jazyk'''
add_lang = '''Pridať jazyk'''

[web]
add_to_chrome = '''Pridať do prehliadača Chrome'''
add_to_firefox = '''Pridať do Firefoxu'''
add_to_browser = '''Pridajte do prehliadača'''
get_premium_button = '''Prejsť na Premium'''
faq_title = '''Často kladené otázky'''
faq_other_questions = '''Máte ešte nejaké otázky?'''
faq_ask = '''Požiadajte o podporu'''
landing_nav_links_0 = '''Prémium'''
landing_nav_links_1 = '''Podpora'''
landing_hero_quote = '''Jedno z najlepších rozšírení'''
landing_hero_author = '''Eric Griffith'''
landing_hero_source = '''PC magazín'''
landing_hero_title = '''Stiahnite si akékoľvek video odkiaľkoľvek'''
landing_hero_subtitle = '''Jedno rozšírenie na sťahovanie a ukladanie videí z takmer akéhokoľvek webu.'''
landing_hero_signature = '''Jednoduché. Efektívne. Súkromné.'''
landing_hero_badges_0 = '''Bezplatné použitie'''
landing_hero_badges_1 = '''Nevyžaduje sa žiadna registrácia'''
landing_hero_badges_2 = '''Hodnotenie 23 000+'''
landing_hero_badges_3 = '''5.0'''
landing_section_1_simple_by_design_title = '''Dizajnovo jednoduchý'''
landing_section_1_simple_by_design_paragraph = '''Po zistení videa sa zobrazí ikona, aby ste mohli sťahovať.'''
landing_section_1_simple_by_design_items_0 = '''Nie je potrebný žiadny externý softvér'''
landing_section_1_simple_by_design_items_1 = '''Jednoduché nastavenie'''
landing_section_1_simple_by_design_items_2 = '''Stačí nájsť video a stiahnuť si ho'''
landing_section_2_powerful_reliable_title = '''Výkonný a spoľahlivý'''
landing_section_2_powerful_reliable_paragraph = '''Stiahnite si videá z tisícok webových stránok vo všetkých hlavných formátoch. Vychutnajte si HD kvalitu a maximálnu rýchlosť sťahovania.'''
landing_section_3_privacy_title = '''Vaše súkromie je na prvom mieste'''
landing_section_3_privacy_paragraph = '''Veríme v slobodný a otvorený web a vo vaše právo kontrolovať svoj obsah.'''
landing_section_3_privacy_items_0 = '''Nezhromažďujeme vaše údaje o prehliadaní.'''
landing_section_3_privacy_items_1 = '''Nikdy žiadne sledovanie.'''
landing_section_4_stats_stats_0_value = '''Viac ako 20 miliónov používateľov'''
landing_section_4_stats_stats_0_description = '''zo 165 krajín'''
landing_section_4_stats_stats_1_value = '''20 rokov'''
landing_section_4_stats_stats_1_description = '''Postavené s vášňou a starostlivosťou'''
landing_section_4_stats_stats_2_value = '''1 000+'''
landing_section_4_stats_stats_2_description = '''podporované webové stránky'''
landing_section_5_premium_title_a = '''Prejsť na prémium za'''
landing_section_5_premium_title_b = '''neobmedzená moc'''
landing_section_5_premium_paragraph = '''Odomknite neobmedzené sťahovanie a rýchlejšie spracovanie. Podporte projekt a vychutnajte si plný zážitok z Pomocníka na sťahovanie videa.'''
landing_section_6_browsers_label = '''Dostupné v prehliadači vášho internetového obchodu'''
landing_cta_banner_title = '''Najdôveryhodnejší nástroj na sťahovanie videa pre váš prehliadač'''
landing_cta_banner_paragraph = '''Používajú ho milióny ľudí už takmer 20 rokov'''
landing_footer_paragraph = '''Najdôveryhodnejšie rozšírenie na sťahovanie videa pre Chrome, Firefox a Edge.'''
landing_footer_links_1 = '''Dokumentácia'''
landing_footer_links_2 = '''Kontaktovať'''
landing_footer_links_3 = '''Zásady ochrany osobných údajov'''
landing_footer_title = '''Produkt'''
landing_footer_title_2 = '''Podpora'''
landing_footer_title_3 = '''Stiahnuť'''
landing_footer_donate = '''Darovať'''
landing_faq_items_0_question = '''Čo je Pomocník na sťahovanie videa?'''
landing_faq_items_0_answer = '''Video Download Helper je rozšírenie prehliadača, ktoré vám umožňuje zisťovať a sťahovať video a audio obsah z mnohých webových stránok priamo z vášho prehliadača.'''
landing_faq_items_1_question = '''Je pomocník na sťahovanie videa zadarmo?'''
landing_faq_items_1_answer = '''Áno - a zostane zadarmo. Video Download Helper si môžete nainštalovať a používať bezplatne a bez časového obmedzenia. Bezplatná verzia vám už umožňuje sťahovať videá z tisícok webových stránok a využívať všetky základné funkcie. Pre väčšinu používateľov je bezplatná verzia viac než dostatočná na každodenné sťahovanie. Ak potrebujete pokročilé funkcie a neobmedzené sťahovanie, môžete si zakúpiť jednorazovú prémiovú licenciu.'''
landing_faq_items_2_question = '''V ktorých prehliadačoch môžem použiť Pomocníka na sťahovanie videa?'''
landing_faq_items_2_answer = '''Video Download Helper je k dispozícii pre Google Chrome, Firefox a Microsoft Edge. Môžete si ho nainštalovať priamo z oficiálnych obchodov prehliadača. Ak máte prémiovú licenciu, vaša licencia funguje vo všetkých prehliadačoch.'''
landing_faq_items_3_question = '''Aké typy videí si môžem stiahnuť?'''
landing_faq_items_3_answer = '''Video Download Helper zisťuje a sťahuje väčšinu webových video formátov, vrátane štandardných MP4 videí, streamingových formátov (HLS, DASH), vložených videí na tisíckach webových stránok a audio streamov (MP3 a ďalšie). Funguje na platformách sociálnych médií, vzdelávacích stránkach, spravodajských weboch, streamovacích službách a mnohých ďalších platformách. Rozšírenie automaticky rozpozná dostupné médiá, keď navštívite stránku.'''
landing_faq_items_4_question = '''Je pomocník na sťahovanie videa bezpečný?'''
landing_faq_items_4_answer = '''Usilovne pracujeme na tom, aby bol Pomocník na sťahovanie videa pre našich používateľov bezpečný: dostupný v oficiálnych obchodoch prehliadačov (Internetový obchod Chrome, doplnky Firefoxu), používaný miliónmi používateľov na celom svete, žiadny spyware, žiadny ďalší predaj údajov, pravidelne aktualizovaný a udržiavaný. Video Download Helper bol vyvinutý a dôveryhodný už takmer 20 rokov. Vaše súkromie a bezpečnosť sú prioritou.'''
landing_faq_items_5_question = '''Čo obsahuje platená verzia?'''
landing_faq_items_5_answer = '''Prémiová licencia odomyká plnú silu Video Download Helper: odstraňuje vodoznak z konverzií, umožňuje neobmedzené vysokokvalitné konverzie videa, rýchlejšie spracovanie, pokročilé funkcie sťahovania, podporuje ďalší vývoj. Ak sťahujete videá pravidelne, licencia sa rýchlo vyplatí.'''
premium_hero_title = '''Inovujte svoj plán'''
premium_hero_subtitle = '''Vyskúšajte to zadarmo a inovujte, aby ste odomkli neobmedzené sťahovanie'''
premium_card_basic_title = '''Základná verzia'''
premium_card_basic_description = '''Navždy zadarmo. Ideálne na začiatok.'''
premium_card_basic_features_included_0 = '''Úplne zadarmo'''
premium_card_basic_features_included_1 = '''Stiahnite si svoje obľúbené videá'''
premium_card_basic_features_excluded_0 = '''Žiadne pokročilé funkcie'''
premium_card_premium_title = '''Získajte doživotnú licenciu'''
premium_card_premium_badges_0 = '''Najlepšia hodnota'''
premium_card_premium_description = '''Odomknite všetko. Jedna platba, doživotný prístup.'''
premium_card_premium_features_included_0 = '''Neobmedzené sťahovanie'''
premium_card_premium_features_included_1 = '''Maximálna kvalita a rýchlosť'''
premium_card_premium_features_included_2 = '''Pokročilé funkcie'''
premium_card_premium_features_included_3 = '''Prioritná podpora'''
premium_card_premium_button = '''Inovujte na prémiové'''
premium_faq_items_0_question = '''Ako funguje platba?'''
premium_faq_items_0_answer = '''Platby spracováva Stripe, ktorý ponúka široké možnosti (Amazon Pay, PayPal, kreditné karty, Alipay atď.). Nemáme prístup k vašim bankovým informáciám a nič nie je uložené na našich serveroch.'''
premium_faq_items_1_question = '''Môžem použiť svoju licenciu na viacerých zariadeniach?'''
premium_faq_items_1_answer = '''Svoju prémiovú licenciu môžete použiť na všetkých svojich zariadeniach a vo všetkých prehliadačoch. Ak ju chcete aktivovať, kedykoľvek kliknite na „Obnoviť nákup“.'''
premium_faq_items_2_question = '''Sú zahrnuté aktualizácie?'''
premium_faq_items_2_answer = '''Áno, doživotný prístup, všetky verzie, bez dátumu vypršania platnosti.'''
premium_faq_items_3_question = '''Čo sa stane po vypršaní platnosti mojej licencie?'''
premium_faq_items_3_answer = '''Vaša doživotná licencia nikdy nevyprší.'''
premium_supported_payment_methods = '''Podporované spôsoby platby'''
premium_free = '''Zadarmo'''
premium_subscription_title = '''Získajte ročné predplatné'''
premium_per_year = '''/ rok'''
premium_proceed_to_payment = '''Pokračujte k platbe'''
premium_plan_subscription_title = '''Predplatné'''
premium_plan_subscription_period = '''12 mesiacov'''
premium_plan_subscription_tagline = '''Cena kávy/mesiac'''
premium_subscribe_button = '''Prihlásiť sa na odber'''
premium_plan_lifetime_title = '''Kúpiť licenciu'''
premium_plan_lifetime_period = '''Pre život'''
premium_plan_lifetime_tagline = '''Zaplaťte raz, používajte navždy'''
premium_buy_button = '''Kúpiť'''
issue_title = '''Obnovuje sa nákup'''
issue_submit = '''Odoslať'''
issue_thank_you = '''Ďakujem'''
issue_back = '''Späť'''
issue_enter_email = '''Ak chcete obnoviť nákup, zadajte e-mailovú adresu, ktorú ste použili na zakúpenie licencie:'''
issue_email_sent = '''Práve sme vám poslali e-mail s odkazom, ktorý aktivuje váš produkt.'''
issue_or_digit = '''Alebo môžete zadať aj 6-miestny kód, ktorý sme vám poslali:'''
issue_just_digit = '''Zadajte 6-miestny kód, ktorý sme vám poslali:'''
issue_i_have_a_code = '''(Kliknite sem, ak už máte kód)'''
issue_i_have_a_key = '''(Kliknite sem, ak máte licenčný kľúč)'''
issue_key = '''Zadajte svoj licenčný kľúč pomocníka na sťahovanie videa:'''
rapid_release_title = '''Rýchle vydanie pre pokročilých používateľov'''
rapid_release_paragraph = '''Toto je predbežná verzia doplnku, ktorá obsahuje častejšie aktualizácie v porovnaní so štandardným vydaním.'''
rapid_release_primary_button = '''Pridať do Firefoxu'''
rapid_release_note = '''Dostupné iba vo Firefoxe.'''
activation_title = '''Vaša licencia je teraz aktívna'''
activation_subtitle = '''Váš nákup je prepojený s vašou e-mailovou adresou.'''
activation_loading = '''Aktivácia'''
activate_error = '''Chyba'''
activate_no_addon_found = '''Nebol nájdený žiadny doplnok. Je doplnok nainštalovaný?'''
activate_no_method_found = '''Nenašla sa žiadna metóda.'''
activate_help_me = '''Pomôžte mi.'''
welcome_hero_title = '''gratulujem! Všetko je pripravené'''
welcome_hero_subtitle = '''Video Download Helper je pripravený na použitie. Teraz si ho môžete pripnúť do prehliadača.'''
welcome_card_items_0 = '''Pripnite pomocníka na sťahovanie videa, aby ste mali prístup vždy, keď to potrebujete'''
welcome_card_items_1 = '''Kliknite na ikonu špendlíka'''
goodbye_hero_title = '''Ďakujeme, že ste vyskúšali Pomocníka na sťahovanie videa'''
goodbye_hero_subtitle = '''Vždy sa snažíme zlepšovať.'''
goodbye_form_question = '''Mohli by ste nám chvíľu povedať, prečo ste odinštalovali Pomocníka na sťahovanie videa?'''
goodbye_form_answer_options_0 = '''Žiadna podpora YouTube'''
goodbye_form_answer_options_1 = '''Príliš drahé'''
goodbye_form_answer_options_2 = '''Moje sťahovanie zlyhalo'''
goodbye_form_answer_options_3 = '''Rozšírenie nezistilo moje video'''
goodbye_form_answer_options_4 = '''Stiahnutý súbor sa neprehral'''
goodbye_form_answer_options_5 = '''Iné'''
goodbye_form_placeholder = '''Dodatočný komentár'''
goodbye_form_cta = '''Odoslať spätnú väzbu'''
goodbye_thank_you = '''Ďakujem'''
