# tr.toml - v10.5.2.2
[addon]
appDesc = '''Web'den Videolar İndirin.'''
restore_purchase_button = '''Satın alımı geri yükle'''
get_premium_button = '''Premium al'''
get_premium_description_button = '''Sınırsız İndirme'''
back = '''Geri'''
rm_notifications_all = '''Tüm bildirimleri temizle'''
waiting_for_media = '''Medya için bekleniyor...'''
nomedia_title = '''Aradığın medyayı göremiyor musun?'''
nomedia_description = '''Medya tespitine yardımcı olmak için videoyu başlat (varsa reklamları atla). Veya kayıp medyayı raporla.'''
nomedia_reload_button = '''Tespite zorla'''
nomedia_reload_button_tooltip = '''Zorla sayfayı yenile (çerezleri temizler)'''
show_nomedia_button = '''Video yok mu?'''
show_nomedia_button_tooltip = '''Eğer videonu bulamıyorsan buraya tıkla'''
setting_button_tooltip = '''Ayarlar'''
history_button_tooltip = '''İndirme Geçmişini Göster'''
show_all_history_button = '''tümünü göster'''
complete_title = '''Tamamlanmış'''
hide_complete_button = '''gizle'''
translate_button_tooltip = '''VDH çevirisine yardımcı ol'''
help_button_tooltip = '''Yardım'''
open_source_tab_button_tooltip = '''Kaynak sekmesini aç'''
retry_download_button_tooltip = '''İndirmeyi tekrar dene'''
delete_file_button_tooltip = '''Dosyayı sil'''
download_directory_button_tooltip = '''İndirme klasörünü göster'''
clear_downloaded_tooltip = '''Bitmiş indirmeleri temizle'''
show_in_popup_button_tooltip = '''Açılır pencerede göster'''
show_in_sidebar_button_tooltip = '''Kenar çubuğunda göster'''
video_not_playing_button_tooltip = '''Video oynamıyor mu?'''
play = '''Oynat'''
warn_drm_tooltip = '''DRM algılandı'''
version_title = '''Sürüm'''
account_title = '''Hesap'''
one_hundred_downloads_title = '''100 video indirdin!'''
leave_review_description = '''Video Download Helper'ı beğendiğini umuyoruz :) Eklenti web sitesine hoş bir inceleme yazman mümkün mü?'''
leave_review_button = '''İnceleme yaz'''
account_status = '''Durum'''
account_status_premium = '''Premium ($1)'''
free_account = '''Ücretsiz plan'''
copy_to_clipboard = '''Bilgiyi panoya kopyala'''
my_account_button = '''Hesabım'''
download_title = '''İndirmeler'''
show_notification = '''İndirme tamamlanınca bildirim göster'''
max_parallel_downloads = '''Maks eş zamanlı indirme'''
saveas_detected_warning = '''İndirme işlemi tamamlandıktan sonra tarayıcınızın 'Farklı Kaydet' iletişim kutusunu gösterdiğini tespit ettik. Bu seçeneği tarayıcı ayarlarınızdan devre dışı bırakmanızı öneririz.'''
change_saveas_setting = '''Ayarı değiştir'''
download_directory_title = '''İndirme dizini'''
download_directory_description = '''Videolar, tarayıcının varsayılan indirme dizinine indirilir. Ayrıca bir alt dizin de belirtebilirsiniz. Web sitesine özel indirme dizinleri, akıllı adlandırma aracıyla ayarlanabilir.'''
change_browser_download_directory = '''Tarayıcı indirme dizinini değiştir'''
bad_download_subdirectory_warning = ''' Belirttiğiniz alt dizin geçerli değil.'''
download_subdirectory = '''indirme altdizini'''
private_browsing_title = '''Gizli gezinme'''
private_browsing_warning = '''Video Download Helper, Özel/Gizli pencerelerde etkin değil. Bu seçeneği manuel olarak açmanız gerekiyor (zorunlu değil).'''
private_browsing_notifications = '''Gizli indirmeler için bildirim göster'''
private_browsing_button = '''Gizli gezinme ayarını değiştir'''
throttle_youtube = ''' YouTube indirmelerini yavaşlatın (daha yavaş indirme, ancak engellenme olasılığı daha düşük)'''
prefer_original_audio = '''Orijinal sesi tercih et'''
settings_history_title = '''Geçmiş'''
transient_history_description = '''Panelde tamamlanmış indirmeleri göster'''
history_limit = '''X gün sonra indirme geçmişini unut'''
appearance_title = '''Görünüm'''
theme_title = '''Tema'''
theme_light = '''aydınlık'''
theme_dark = '''karanlık'''
theme_system = '''sistem'''
popup_size_title = '''Pencere boyutu'''
popup_size_small = '''Küçük'''
popup_size_medium = '''Orta'''
popup_size_big = '''Büyük'''
font_size_title = '''Yazı boyutu'''
font_size_default = '''Varsayılan'''
font_size_large = '''Büyük'''
font_size_verylarge = '''Çok büyük'''
panel_position_title = '''Panel pozisyonu'''
use_popup = '''Açılır pencerede göster'''
use_sidebar = '''Kenar çubuğunda göster'''
behavior_title = '''Davranış'''
controls_title = '''Kontroller'''
show_in_context_menu = '''Sayfada sağ tık menüsünden komutlara eriş'''
restart_addon = '''Eklentiyi yeniden yükle'''
reset_settings = '''Ayarları sıfırla'''
prefered_quality = '''Tercih edilen video kalitesi'''
prefered_quality_highest = '''En iyi (yavaş indirme, yüksek çözünürlülük)'''
prefered_quality_1080p = '''1080p (iyi, varsayılan)'''
prefered_quality_720p = '''720p (hızlı indirme, düşük çözünürlükük)'''
prefered_quality_480p = '''480p (hızlı indirme, düşük çözünürlülük)'''
prefer_mkv = '''mümkün olduğunda MKV olarak indir'''
preview_mode_title = '''Medya önizlemesi'''
preview_mode_none = '''Devredışı'''
preview_mode_video = '''Kısa video önizlemesi'''
preview_mode_image = '''Resim'''
media_discovered_ordering_title = '''Medya sıralama stratejisi'''
order_media_smart = ''' Akıllı sıralama (önerilir)'''
order_media_by_newest = '''Önce en yeni'''
order_media_by_oldest = '''Önce en eski'''
settings_subtitles_title = '''Tercih Edilen Altyazı Dilleri'''
settings_audio_tracks_title = '''Tercih Edilen Ses Parçaları'''
history_title = '''İndirme Geçmişi'''
history_warning = '''İndirme geçmişinizi kaydetmiyoruz. Video Download Helper'ın indirme geçmişini hatırlamasını ister misin?'''
history_warning_2 = '''Endişelenmeyin, her şey bilgisayarınızda kalır. Gizliliğinize değer veriyoruz.'''
enable_history = '''Geçmişi Etkinleştir'''
clear_history = '''Geçmişi Temizle'''
disable_history = '''Geçmişimi hatırlama'''
no_downloads_yet = '''Henüz giriş yok.'''
download_failed = '''İndirme başarısız'''
download_failed_description = '''Maalesef söz konusu medyayı indirmeyi başaramadık. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!).'''
download_interrupted = '''İndirme kesintiye uğradı'''
download_interrupted_description = '''Dosyanızı indirmeyi başardık, ancak bir ağ sorunu oluştu, bu nedenle dosya beklenenden daha kısa olabilir. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!).'''
download_with_drm_failed_description = '''Bir sorun oluştu. Bu videonun DRM korumasına sahip olduğunu düşünüyoruz. DRM korumasına sahip videoları desteklemiyoruz.'''
no_youtube = '''Youtube'dan indirmeye izin verilmiyor'''
no_youtube_description = '''Ne yazık ki Chrome Web Mağazası YouTube videolarını indirmek için eklentilere izin vermiyor, bu nedenle eklentinin Chrome sürümüne bu özelliği ekleyemedik.'''
no_youtube_description_2 = '''Lütfen Firefox veya Microsoft Edge kullanın'''
premium_required = '''Premium statü gerekli'''
premium_yt_required_description = '''Premium statüsü olmadan YouTube indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir.'''
premium_hls_required_description = '''Premium statüsü olmadan HLS veya MPD indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir.'''
premium_all_required_description = '''Premium üyeliğiniz yoksa, bir önceki indirmeden 2 saat sonra indirme işlemi gerçekleştirilebilir.'''
youtube_too_many_downloads = '''Eyvah, YouTube engellenmiş görünüyor'''
youtube_too_many_downloads_description = '''YouTube bazen istenebilecek video sayısını sınırlayabilir. Maalesef yapabileceğimiz bir şey yok. Daha sonra tekrar deneyin.'''
stop = '''Dur'''
cancel = '''İptal'''
copy_url = '''URL'yi Kopyala'''
always_copy_url = '''Her zaman URL'yi kopyala'''
download_button = '''İndir'''
download_as_button_and_menu = '''Farklı İndir...'''
rename_short = '''Yeniden Adlandır'''
always_download_as_menu = '''Her Zaman Farklı İndir...'''
download_audio_button = '''Ses'''
download_audio_and_video_menu = '''Ses & Video İndir'''
download_audio_only_menu = '''Ses İndir'''
audio_only_for_this_website = '''Bu website için her zaman sadece ses'''
details = '''Detaylar'''
report = '''Bildir'''
reporting = '''Bildiriliyor...'''
reported_thankyou = '''Teşekkürler!'''
move_lang_up = '''Yukarı Taşı'''
move_lang_down = '''Aşağı Taşı'''
remove_lang = '''Dili Kaldır'''
add_lang = '''Dil Ekle'''

[web]
add_to_chrome = '''Chrome’a Ekle'''
add_to_firefox = '''Firefox’a Ekle'''
add_to_browser = '''Tarayıcınıza Ekleyin'''
get_premium_button = '''Premium’a Geçin'''
faq_title = '''Sıkça Sorulan Sorular'''
faq_other_questions = '''Başka Sorularınız mı Var?'''
faq_ask = '''Destek Ekibine Sorun'''
landing_nav_links_0 = '''Premium'''
landing_nav_links_1 = '''Destek'''
landing_hero_quote = '''En İyi Eklentilerden Biri'''
landing_hero_author = '''Eric Griffith'''
landing_hero_source = '''PC Magazine'''
landing_hero_title = '''Her Yerden, İstediğiniz Videoyu İndirin'''
landing_hero_subtitle = '''Neredeyse Tüm İnternet Sitelerindeki Videoları İndirip Kaydetmenizi Sağlayan Tek Bir Eklenti.'''
landing_hero_signature = '''Basit. Verimli. Güvenli.'''
landing_hero_badges_0 = '''Ücretsiz Kullanım'''
landing_hero_badges_1 = '''Kayıt Gerekmez'''
landing_hero_badges_2 = '''23 Binden Fazla Değerlendirme'''
landing_hero_badges_3 = '''5.0'''
landing_section_1_simple_by_design_title = '''Sade ve Kullanışlı Tasarım'''
landing_section_1_simple_by_design_paragraph = '''Bir video algılandığında, indirmeye hazır olduğunuzu gösteren bir simge belirir.'''
landing_section_1_simple_by_design_items_0 = '''Ek Bir Yazılım Gerekmez'''
landing_section_1_simple_by_design_items_1 = '''Kolay Kurulum'''
landing_section_1_simple_by_design_items_2 = '''Videoyu Bulun ve Hemen İndirin'''
landing_section_2_powerful_reliable_title = '''Güçlü ve Güvenilir'''
landing_section_2_powerful_reliable_paragraph = '''Binlerce internet sitesindeki videoları tüm popüler formatlarda indirin. HD kalitenin ve maksimum indirme hızının keyfini çıkarın.'''
landing_section_3_privacy_title = '''Gizliliğiniz Her Şeyden Önce Gelir'''
landing_section_3_privacy_paragraph = '''Özgür ve açık bir internete, içerikleriniz üzerinde kontrol sahibi olma hakkınıza inanıyoruz.'''
landing_section_3_privacy_items_0 = '''Tarama Verilerinizi Toplamıyoruz.'''
landing_section_3_privacy_items_1 = '''Asla Takip Etmiyoruz.'''
landing_section_4_stats_stats_0_value = '''20 Milyondan Fazla Kullanıcı'''
landing_section_4_stats_stats_0_description = '''165 Ülkeden'''
landing_section_4_stats_stats_1_value = '''20 yıl'''
landing_section_4_stats_stats_1_description = '''Tutku ve Özenle Geliştirildi'''
landing_section_4_stats_stats_2_value = '''1,000+'''
landing_section_4_stats_stats_2_description = '''Desteklenen İnternet Siteleri'''
landing_section_5_premium_title_a = '''İçin Premium’a Geçin '''
landing_section_5_premium_title_b = '''Sınırsız Gücün Kilidini Açın'''
landing_section_5_premium_paragraph = '''Sınırsız indirme ve daha hızlı işlem özelliklerinin kilidini açın. Projeye destek olun ve Video DownloadHelper deneyiminin tamamından yararlanın.'''
landing_section_6_browsers_label = '''Tarayıcınızın Eklenti Mağazasında Mevcut'''
landing_cta_banner_title = '''Tarayıcınız İçin En Güvenilir Video İndirme Aracı'''
landing_cta_banner_paragraph = '''Yaklaşık 20 Yıldır Milyonlarca Kişi Tarafından Kullanılıyor'''
landing_footer_paragraph = '''Chrome, Firefox ve Edge için en güvenilir video indirme eklentisi.'''
landing_footer_links_1 = '''Dokümantasyon'''
landing_footer_links_2 = '''İletişim'''
landing_footer_links_3 = '''Gizlilik Politikası'''
landing_footer_title = '''Ürün'''
landing_footer_title_2 = '''Destek'''
landing_footer_title_3 = '''İndir'''
landing_footer_donate = '''Bağış Yap'''
landing_faq_items_0_question = '''Video DownloadHelper Nedir?'''
landing_faq_items_0_answer = '''Video DownloadHelper, birçok internet sitesindeki video ve ses içeriklerini doğrudan tarayıcınız üzerinden algılayıp indirmenizi sağlayan bir tarayıcı eklentisidir.'''
landing_faq_items_1_question = '''Video DownloadHelper Ücretsiz mi?'''
landing_faq_items_1_answer = '''Evet, üstelik her zaman ücretsiz kalacak. Video DownloadHelper’ı herhangi bir ücret ödemeden ve süre sınırı olmadan yükleyip kullanabilirsiniz. Ücretsiz sürüm, binlerce internet sitesinden video indirmenize ve tüm temel özellikleri kullanmanıza olanak tanır. Çoğu kullanıcı için ücretsiz sürüm, günlük indirme ihtiyaçlarını fazlasıyla karşılar. Gelişmiş özelliklere ve sınırsız indirme imkanına ihtiyaç duyarsanız tek seferlik ödeme ile Premium lisans satın alabilirsiniz.'''
landing_faq_items_2_question = '''Video Download Helper’ı Hangi Tarayıcılarda Kullanabilirim?'''
landing_faq_items_2_answer = '''Video DownloadHelper; Google Chrome, Firefox ve Microsoft Edge tarayıcılarında kullanılabilir. Eklentiyi doğrudan tarayıcıların resmî eklenti mağazalarından yükleyebilirsiniz. Premium lisansınız varsa lisansınızı tüm tarayıcılarda kullanabilirsiniz.'''
landing_faq_items_3_question = '''Hangi Tür Videoları İndirebilirim?'''
landing_faq_items_3_answer = '''Video DownloadHelper; standart MP4 videoları, yayın formatları (HLS ve DASH), binlerce internet sitesindeki gömülü videolar ve ses akışları (MP3 ve daha fazlası) dâhil olmak üzere çoğu web video formatını algılayıp indirebilir. Sosyal medya platformlarında, eğitim sitelerinde, haber sitelerinde, yayın hizmetlerinde ve daha birçok platformda çalışır. Bir sayfayı ziyaret ettiğinizde kullanılabilir medya içerikleri eklenti tarafından otomatik olarak algılanır.'''
landing_faq_items_4_question = '''Video Download Helper Güvenli mi?'''
landing_faq_items_4_answer = '''Video DownloadHelper’ı kullanıcılarımız için güvenli hâle getirmek amacıyla büyük bir özenle çalışıyoruz. Eklentimiz resmî tarayıcı mağazalarında (Chrome Web Mağazası ve Firefox Eklentileri) sunulur, dünya genelinde milyonlarca kişi tarafından kullanılır, casus yazılım içermez ve kullanıcı verilerini satmaz. Ayrıca düzenli olarak güncellenir ve geliştirilmeye devam eder. Yaklaşık 20 yıldır geliştirilen ve güvenle kullanılan Video DownloadHelper’da gizliliğiniz ve güvenliğiniz her zaman önceliğimizdir.'''
landing_faq_items_5_question = '''Ücretli Sürüm Neler Sunar?'''
landing_faq_items_5_answer = '''Premium lisans, Video DownloadHelper’ın tüm gücünden yararlanmanızı sağlar. Dönüştürülen videolardaki filigranı kaldırır, sınırsız ve yüksek kaliteli video dönüştürme imkânı sunar, işlemleri hızlandırır, gelişmiş indirme özelliklerini kullanıma açar ve projenin geliştirilmeye devam etmesine destek olur. Düzenli olarak video indiriyorsanız lisans, kısa sürede ödediğiniz ücrete değer.'''
premium_hero_title = '''Planınızı Yükseltin'''
premium_hero_subtitle = '''Ücretsiz deneyin, sınırsız indirmelerin kilidini açmak için planınızı yükseltin.'''
premium_card_basic_title = '''Temel Sürüm'''
premium_card_basic_description = '''Daima ücretsiz. Başlamak için ideal.'''
premium_card_basic_features_included_0 = '''Tamamen Ücretsiz'''
premium_card_basic_features_included_1 = '''Favori Videolarınızı İndirin'''
premium_card_basic_features_excluded_0 = '''Gelişmiş Özellikler Dâhil Değildir'''
premium_card_premium_title = '''Ömür Boyu Lisansınızı Alın'''
premium_card_premium_badges_0 = '''En Avantajlı Seçenek'''
premium_card_premium_description = '''Tüm özelliklerin kilidini açın. Tek ödeme yapın, ömür boyu kullanın.'''
premium_card_premium_features_included_0 = '''Sınırsız İndirme'''
premium_card_premium_features_included_1 = '''Maksimum Kalite ve Hız'''
premium_card_premium_features_included_2 = '''Gelişmiş Özellikler'''
premium_card_premium_features_included_3 = '''Öncelikli Destek'''
premium_card_premium_button = '''Premium’a Geçin'''
premium_faq_items_0_question = '''Ödeme İşlemi Nasıl Gerçekleşir?'''
premium_faq_items_0_answer = '''Ödemeler; Amazon Pay, PayPal, kredi kartları ve Alipay gibi çok sayıda ödeme seçeneği sunan Stripe tarafından güvenli bir şekilde işlenir. Bankacılık bilgilerinize erişemeyiz ve bu bilgiler sunucularımızda saklanmaz.'''
premium_faq_items_1_question = '''Lisansımı Birden Fazla Cihazda Kullanabilir miyim?'''
premium_faq_items_1_answer = '''Premium lisansınızı tüm cihazlarınızda ve tüm tarayıcılarınızda kullanabilirsiniz. Lisansınızı etkinleştirmek için istediğiniz zaman “Satın Alımı Geri Yükle” seçeneğine tıklayın.'''
premium_faq_items_2_question = '''Güncellemeler Lisansa Dâhil mi?'''
premium_faq_items_2_answer = '''Evet. Ömür boyu erişim sayesinde tüm sürümlerden yararlanabilirsiniz. Lisansınızın son kullanma tarihi yoktur.'''
premium_faq_items_3_question = '''Lisansımın Süresi Dolduğunda Ne Olur?'''
premium_faq_items_3_answer = '''Ömür boyu lisansınızın süresi hiçbir zaman dolmaz.'''
premium_supported_payment_methods = '''Desteklenen Ödeme Yöntemleri'''
premium_free = '''Ücretsiz'''
premium_subscription_title = '''Yıllık Aboneliğinizi Başlatın'''
premium_per_year = '''/ yıl'''
premium_proceed_to_payment = '''Ödemeye Devam Et'''
premium_plan_subscription_title = '''Abonelik'''
premium_plan_subscription_period = '''12 Ay'''
premium_plan_subscription_tagline = '''Aylık Bir Kahve Fiyatına'''
premium_subscribe_button = '''Abone Ol'''
premium_plan_lifetime_title = '''Lisans Satın Al'''
premium_plan_lifetime_period = '''Ömür Boyu'''
premium_plan_lifetime_tagline = '''Bir Kez Ödeyin, Ömür Boyu Kullanın'''
premium_buy_button = '''Satın Al'''
issue_title = '''Satın Alım Geri Yükleniyor'''
issue_submit = '''Gönder'''
issue_thank_you = '''Teşekkür Ederiz'''
issue_back = '''Geri Dön'''
issue_enter_email = '''Satın alımınızı geri yüklemek için lisansınızı satın alırken kullandığınız e-posta adresini girin:'''
issue_email_sent = '''Ürününüzü etkinleştirecek bağlantıyı içeren bir e-postayı az önce size gönderdik.'''
issue_or_digit = '''Dilerseniz size gönderdiğimiz 6 haneli kodu da girebilirsiniz:'''
issue_just_digit = '''Size gönderdiğimiz 6 haneli kodu girin:'''
issue_i_have_a_code = '''(Zaten bir kodunuz varsa buraya tıklayın.)'''
issue_i_have_a_key = '''(Bir lisans anahtarınız varsa buraya tıklayın.)'''
issue_key = '''Video DownloadHelper lisans anahtarınızı girin:'''
rapid_release_title = '''İleri Düzey Kullanıcılar İçin Hızlı Sürüm'''
rapid_release_paragraph = '''Bu, standart sürüme kıyasla daha sık güncelleme alan bir ön sürümdür.'''
rapid_release_primary_button = '''Firefox’a Ekle'''
rapid_release_note = '''Yalnızca Firefox’ta Kullanılabilir'''
activation_title = '''Lisansınız Artık Etkin'''
activation_subtitle = '''Satın alımınız e-posta adresinizle ilişkilendirildi.'''
activation_loading = '''Etkinleştirme'''
activate_error = '''Hata'''
activate_no_addon_found = '''Eklenti bulunamadı. Eklentinin yüklü olduğundan emin misiniz?'''
activate_no_method_found = '''Uygun bir yöntem bulunamadı.'''
activate_help_me = '''Yardım Al'''
welcome_hero_title = '''Tebrikler! Her Şey Hazır'''
welcome_hero_subtitle = '''Video DownloadHelper kullanıma hazır. Artık eklentiyi tarayıcınıza sabitleyebilirsiniz.'''
welcome_card_items_0 = '''Video DownloadHelper’a ihtiyaç duyduğunuz her an kolayca erişmek için eklentiyi tarayıcınıza sabitleyin.'''
welcome_card_items_1 = '''Sabitleme simgesine tıklayın'''
goodbye_hero_title = '''Video DownloadHelper’ı Denediğiniz İçin Teşekkür Ederiz'''
goodbye_hero_subtitle = '''Kendimizi sürekli geliştirmeye çalışıyoruz.'''
goodbye_form_question = '''Video DownloadHelper’ı neden kaldırdığınızı bize anlatmak için kısa bir zaman ayırabilir misiniz?'''
goodbye_form_answer_options_0 = '''YouTube Desteği Bulunmuyor'''
goodbye_form_answer_options_1 = '''Çok Pahalı'''
goodbye_form_answer_options_2 = '''İndirme İşlemi Başarısız Oldu'''
goodbye_form_answer_options_3 = '''Eklenti Videomu Algılamadı'''
goodbye_form_answer_options_4 = '''İndirdiğim Dosya Oynatılamadı'''
goodbye_form_answer_options_5 = '''Diğer'''
goodbye_form_placeholder = '''Ek Açıklama'''
goodbye_form_cta = '''Geri Bildirim Gönder'''
goodbye_thank_you = '''Teşekkür Ederiz'''
