# Turkish
# tr.toml - v10.2.53.2
[addon]
appDesc = '''Web'den Videolar İndirin.'''
restore_purchase_button = '''Satın alımı geri yükle'''
get_premium_button = '''Premium al'''
back = '''Geri'''
rm_notifications_all = '''Tüm bildirimleri temizle'''
waiting_for_media = '''Medya için bekleniyor...'''
nomedia_title = '''Aradığın medyayı göremiyor musun?'''
nomedia_description = '''Medya tespitine yardımcı olmak için videoyu başlat (varsa reklamları atla). Veya kayıp medyayı raporla.'''
nomedia_reload_button = '''Tespite zorla'''
nomedia_reload_button_tooltip = '''Zorla sayfayı yenile (çerezleri temizler)'''
show_nomedia_button = '''Video yok mu?'''
show_nomedia_button_tooltip = '''Eğer videonu bulamıyorsan buraya tıkla'''
setting_button_tooltip = '''Ayarlar'''
history_button_tooltip = '''İndirme Geçmişini Göster'''
show_all_history_button = '''tümünü göster'''
complete_title = '''Tamamlanmış'''
hide_complete_button = '''gizle'''
translate_button_tooltip = '''VDH çevirisine yardımcı ol'''
help_button_tooltip = '''Yardım'''
open_source_tab_button_tooltip = '''Kaynak sekmesini aç'''
retry_download_button_tooltip = '''İndirmeyi tekrar dene'''
delete_file_button_tooltip = '''Dosyayı sil'''
download_directory_button_tooltip = '''İndirme klasörünü göster'''
clear_downloaded_tooltip = '''Bitmiş indirmeleri temizle'''
show_in_popup_button_tooltip = '''Açılır pencerede göster'''
show_in_sidebar_button_tooltip = '''Kenar çubuğunda göster'''
video_not_playing_button_tooltip = '''Video oynamıyor mu?'''
play = '''Oynat'''
warn_drm_tooltip = '''DRM algılandı'''
version_title = '''Sürüm'''
account_title = '''Hesap'''
one_hundred_downloads_title = '''100 video indirdin!'''
leave_review_description = '''Video DownloadHelper'ı beğendiğini umuyoruz :) Eklenti web sitesine hoş bir inceleme yazman mümkün mü?'''
leave_review_button = '''İnceleme yaz'''
account_status = '''Durum'''
account_status_premium = '''Premium ($1)'''
free_account = '''Ücretsiz plan'''
copy_to_clipboard = '''Bilgiyi panoya kopyala'''
my_account_button = '''Hesabım'''
download_title = '''İndirmeler'''
show_notification = '''İndirme tamamlanınca bildirim göster'''
max_parallel_downloads = '''Maks eş zamanlı indirme'''
saveas_detected_warning = '''İndirme işlemi tamamlandıktan sonra tarayıcınızın 'Farklı Kaydet' iletişim kutusunu gösterdiğini tespit ettik. Bu seçeneği tarayıcı ayarlarınızdan devre dışı bırakmanızı öneririz.'''
change_saveas_setting = '''Ayarı değiştir'''
download_directory_title = '''İndirme dizini'''
download_directory_description = '''Videolar, tarayıcının varsayılan indirme dizinine indirilir. Ayrıca bir alt dizin de belirtebilirsiniz. Web sitesine özel indirme dizinleri, akıllı adlandırma aracıyla ayarlanabilir.'''
change_browser_download_directory = '''Tarayıcı indirme dizinini değiştir'''
bad_download_subdirectory_warning = ''' Belirttiğiniz alt dizin geçerli değil.'''
download_subdirectory = '''indirme altdizini'''
private_browsing_title = '''Gizli gezinme'''
private_browsing_warning = '''Video DownloadHelper, Özel/Gizli pencerelerde etkin değil. Bu seçeneği manuel olarak açmanız gerekiyor (zorunlu değil).'''
private_browsing_notifications = '''Gizli indirmeler için bildirim göster'''
private_browsing_button = '''Gizli gezinme ayarını değiştir'''
throttle_youtube = ''' YouTube indirmelerini yavaşlatın (daha yavaş indirme, ancak engellenme olasılığı daha düşük)'''
prefer_original_audio = '''Orijinal sesi tercih et'''
settings_history_title = '''Geçmiş'''
transient_history_description = '''Panelde tamamlanmış indirmeleri göster'''
history_limit = '''X gün sonra indirme geçmişini unut'''
appearance_title = '''Görünüm'''
theme_title = '''Tema'''
theme_light = '''aydınlık'''
theme_dark = '''karanlık'''
theme_system = '''sistem'''
popup_size_title = '''Pencere boyutu'''
popup_size_small = '''Küçük'''
popup_size_medium = '''Orta'''
popup_size_big = '''Büyük'''
font_size_title = '''Yazı boyutu'''
font_size_default = '''Varsayılan'''
font_size_large = '''Büyük'''
font_size_verylarge = '''Çok büyük'''
panel_position_title = '''Panel pozisyonu'''
use_popup = '''Açılır pencerede göster'''
use_sidebar = '''Kenar çubuğunda göster'''
behavior_title = '''Davranış'''
controls_title = '''Kontroller'''
show_in_context_menu = '''Sayfada sağ tık menüsünden komutlara eriş'''
restart_addon = '''Eklentiyi yeniden yükle'''
reset_settings = '''Ayarları sıfırla'''
prefered_quality = '''Tercih edilen video kalitesi'''
prefered_quality_highest = '''En iyi (yavaş indirme, yüksek çözünürlülük)'''
prefered_quality_1080p = '''1080p (iyi, varsayılan)'''
prefered_quality_720p = '''720p (hızlı indirme, düşük çözünürlükük)'''
prefered_quality_480p = '''480p (hızlı indirme, düşük çözünürlülük)'''
prefer_mkv = '''mümkün olduğunda MKV olarak indir'''
preview_mode_title = '''Medya önizlemesi'''
preview_mode_none = '''Devredışı'''
preview_mode_video = '''Kısa video önizlemesi'''
preview_mode_image = '''Resim'''
media_discovered_ordering_title = '''Medya sıralama stratejisi'''
order_media_smart = ''' Akıllı sıralama (önerilir)'''
order_media_by_newest = '''Önce en yeni'''
order_media_by_oldest = '''Önce en eski'''
history_title = '''İndirme Geçmişi'''
history_warning = '''İndirme geçmişinizi kaydetmiyoruz. Video DownloadHelper'ın indirme geçmişini hatırlamasını ister misin?'''
history_warning_2 = '''Endişelenmeyin, her şey bilgisayarınızda kalır. Gizliliğinize değer veriyoruz.'''
enable_history = '''Geçmişi Etkinleştir'''
clear_history = '''Geçmişi Temizle'''
disable_history = '''Geçmişimi hatırlama'''
no_downloads_yet = '''Henüz giriş yok.'''
download_failed = '''İndirme başarısız'''
download_failed_description = '''Maalesef söz konusu medyayı indirmeyi başaramadık. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!).'''
download_interrupted = '''İndirme kesintiye uğradı'''
download_interrupted_description = '''Dosyanızı indirmeyi başardık, ancak bir ağ sorunu oluştu, bu nedenle dosya beklenenden daha kısa olabilir. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!).'''
download_with_drm_failed_description = '''Bir sorun oluştu. Bu videonun DRM korumasına sahip olduğunu düşünüyoruz. DRM korumasına sahip videoları desteklemiyoruz.'''
no_youtube = '''Youtube'dan indirmeye izin verilmiyor'''
no_youtube_description = '''Ne yazık ki Chrome Web Mağazası YouTube videolarını indirmek için eklentilere izin vermiyor, bu nedenle eklentinin Chrome sürümüne bu özelliği ekleyemedik.'''
no_youtube_description_2 = '''Lütfen Firefox veya Microsoft Edge kullanın'''
premium_required = '''Premium statü gerekli'''
premium_yt_required_description = '''Premium statüsü olmadan YouTube indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir.'''
premium_hls_required_description = '''Premium statüsü olmadan HLS veya MPD indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir.'''
premium_all_required_description = '''Premium üyeliğiniz yoksa, bir önceki indirmeden 2 saat sonra indirme işlemi gerçekleştirilebilir.'''
youtube_too_many_downloads = '''Eyvah, YouTube engellenmiş görünüyor'''
youtube_too_many_downloads_description = '''YouTube bazen istenebilecek video sayısını sınırlayabilir. Maalesef yapabileceğimiz bir şey yok. Daha sonra tekrar deneyin.'''
stop = '''Dur'''
cancel = '''İptal'''
copy_url = '''URL'yi Kopyala'''
always_copy_url = '''Her zaman URL'yi kopyala'''
download_button = '''İndir'''
download_as_button_and_menu = '''Farklı İndir...'''
rename_short = '''Yeniden Adlandır'''
always_download_as_menu = '''Her Zaman Farklı İndir...'''
download_audio_button = '''Ses'''
download_audio_and_video_menu = '''Ses & Video İndir'''
download_audio_only_menu = '''Ses İndir'''
audio_only_for_this_website = '''Bu website için her zaman sadece ses'''
details = '''Detaylar'''
report = '''Bildir'''
reporting = '''Bildiriliyor...'''
reported_thankyou = '''Teşekkürler!'''
