# uk.toml - v10.2.26.2
[addon]
appDesc = '''Завантажити відео з Інтернету.'''
restore_purchase_button = '''Відновити покупку'''
get_premium_button = '''Отримати преміум-версію'''
back = '''Назад'''
rm_notifications_all = '''Відхилити всі сповіщення'''
waiting_for_media = '''Очікування медіа…'''
nomedia_title = '''Не бачите потрібне відео?'''
nomedia_description = '''Запустіть відео (і пропустіть рекламу, якщо є), щоб допомогти знайти медіа. Або повідомте про відсутність медіа.'''
nomedia_reload_button = '''Примусово запустити пошук'''
nomedia_reload_button_tooltip = '''Примусово перезавантажити сторінку (очистити cookies)'''
show_nomedia_button = '''Немає відео?'''
show_nomedia_button_tooltip = '''Натисніть тут, якщо не можете знайти своє відео'''
setting_button_tooltip = '''Налаштування'''
history_button_tooltip = '''Показати історію завантажень'''
show_all_history_button = '''Показати все'''
complete_title = '''Завершено'''
hide_complete_button = '''Сховати'''
translate_button_tooltip = '''Допомогти з перекладом VDH'''
help_button_tooltip = '''Допомога'''
open_source_tab_button_tooltip = '''Відкрити вкладку з вихідним кодом'''
retry_download_button_tooltip = '''Повторити завантаження'''
delete_file_button_tooltip = '''Видалити файл'''
download_directory_button_tooltip = '''Показати папку завантажень'''
clear_downloaded_tooltip = '''Очистити завершене завантаження'''
show_in_popup_button_tooltip = '''Відкрити у виринаючому вікні'''
show_in_sidebar_button_tooltip = '''Відкрити в бічній панелі'''
video_not_playing_button_tooltip = '''Відео не відтворюється?'''
play = '''Відтворити'''
warn_drm_tooltip = '''Виявлено DRM-захист'''
version_title = '''Версія'''
account_title = '''Акаунт'''
one_hundred_downloads_title = '''Ви завантажили 100 відео!'''
leave_review_description = '''Привіт! 🤚 Video DownloadHelper можна користуватися безкоштовно. Хочете залишити позитивний відгук? Це дуже допоможе 😊.'''
leave_review_button = '''Залишити відгук'''
account_status = '''Статус'''
account_status_premium = '''Premium ($1)'''
free_account = '''Безкоштовний тариф'''
copy_to_clipboard = '''Скопіювати інформацію в буфер обміну'''
my_account_button = '''Мій акаунт'''
download_title = '''Завантаження'''
show_notification = '''Показувати повідомлення після завершення завантаження'''
max_parallel_downloads = '''Максимальна кількість паралельних завантажень'''
saveas_detected_warning = '''Виявлено, що ваш браузер показує діалог «Зберегти як» після завершення завантаження. Радимо вимкнути цю опцію в налаштуваннях браузера.'''
change_saveas_setting = '''Змінити налаштування'''
download_directory_title = '''Каталог для завантажень'''
download_directory_description = '''Відео завантажуються в каталог завантажень браузера за замовчуванням. Ви також можете вказати підкаталог. Каталоги завантажень для конкретних веб-сайтів можна налаштувати за допомогою інструмента SmartNaming.'''
change_browser_download_directory = '''Змінити каталог завантажень браузера'''
bad_download_subdirectory_warning = '''Вказаний вами підкаталог недійсний.'''
download_subdirectory = '''Підкаталог завантажень'''
private_browsing_title = '''Приватний режим'''
private_browsing_warning = '''Video DownloadHelper не працює в приватному режимі.'''
private_browsing_notifications = '''Показувати повідомлення для завантажень у приватному режимі'''
private_browsing_button = '''Змінити налаштування приватного режиму'''
throttle_youtube = '''Обмежити швидкість YouTube (повільніше завантаження, але менший ризик блокування)'''
prefer_original_audio = '''Віддавати перевагу оригінальному звуку'''
settings_history_title = '''Історія'''
transient_history_description = '''Показувати всі завантаження у панелі'''
history_limit = '''Кількість днів збереження історії'''
appearance_title = '''Зовнішній вигляд'''
theme_title = '''Тема'''
theme_light = '''Світла тема'''
theme_dark = '''Темна тема'''
theme_system = '''Системна тема'''
popup_size_title = '''Розмір вікна'''
popup_size_small = '''Маленький'''
popup_size_medium = '''Середній'''
popup_size_big = '''Великий'''
font_size_title = '''Розмір тексту'''
font_size_default = '''За промовчанням'''
font_size_large = '''Великий'''
font_size_verylarge = '''Дуже великий'''
panel_position_title = '''Положення панелі'''
use_popup = '''У виринаючому вікні'''
use_sidebar = '''У бічній панелі'''
behavior_title = '''Поведінка'''
controls_title = '''Управління'''
show_in_context_menu = '''Доступ до меню команд правою кнопкою миші на цільовій сторінці'''
restart_addon = '''Перезапустити розширення'''
reset_settings = '''Скинути налаштування'''
prefered_quality = '''Бажана якість відео'''
prefered_quality_highest = '''Найвища (повільне завантаження, висока роздільність)'''
prefered_quality_1080p = '''1080p (висока за замовчуванням)'''
prefered_quality_720p = '''720p (швидке завантаження, низька роздільність)'''
prefered_quality_480p = '''480p (швидше завантаження, нижча роздільність)'''
prefer_mkv = '''Завантажувати у форматі MKV, коли це можливо'''
preview_mode_title = '''Попередній перегляд медіа'''
preview_mode_none = '''Вимкнено'''
preview_mode_video = '''Перед перегляд короткого відео'''
preview_mode_image = '''Зображення'''
media_discovered_ordering_title = '''Спосіб сортування медіа'''
order_media_smart = '''Розумний (рекомендовано)'''
order_media_by_newest = '''Спочатку новіші'''
order_media_by_oldest = '''Спочатку найстаріші'''
history_title = '''Історія завантажень'''
history_warning = '''Ми не зберігаємо вашу історію завантажень. Хочете, щоб Video DownloadHelper запам’ятовував історію?'''
history_warning_2 = '''Не хвилюйтеся, усі дані залишаються на вашому пристрої. Ми цінуємо вашу конфіденційність.'''
enable_history = '''Увімкнути історію'''
clear_history = '''Очистити історію'''
disable_history = '''Вимкнути історію'''
no_downloads_yet = '''Поки що немає завантажень.'''
download_failed = '''Помилка завантаження'''
download_failed_description = '''Щось пішло не так. Повідомте про помилку, і ми постараємося розібратися (ми анонімно відправляємо URL відео — ми не відслідковуємо вас!).'''
download_interrupted = '''Завантаження перервано'''
download_interrupted_description = '''Файл було частково завантажено, але через проблеми з мережею він може бути коротший, ніж очікувалося. Ми намагаємося підтримувати якомога більше сайтів, тому було б дуже корисно, якби ви повідомили про цю проблему (це анонімно!).'''
download_with_drm_failed_description = '''Щось пішло не так. Ймовірно, це відео захищене DRM. Ми не підтримуємо відео з DRM.'''
no_youtube = '''Завантаження з YouTube заборонено'''
no_youtube_description = '''На жаль, магазин Chrome не допускає розширення для завантаження відео з YouTube, тому ця функція відсутня у версії для Chrome.'''
no_youtube_description_2 = '''Будь ласка, використовуйте Firefox або Microsoft Edge'''
premium_required = '''Потрібен статус Premium'''
premium_yt_required_description = '''Без статусу Premium завантаження з YouTube можливе лише через 2 години після попереднього.'''
premium_hls_required_description = '''Без статусу Premium завантаження HLS або MPD можливо лише через 2 години після попереднього'''
premium_all_required_description = '''Без преміум-статусу завантаження можна виконати лише через 2 години після попереднього.'''
youtube_too_many_downloads = '''Упс, здається, YouTube заблоковано'''
youtube_too_many_downloads_description = '''Іноді YouTube обмежує кількість запитуваних відео. На жаль, ми нічого не можемо з цим вдіяти. Спробуйте пізніше.'''
stop = '''Зупинити'''
cancel = '''Скасувати'''
copy_url = '''Копіювати URL'''
always_copy_url = '''Завжди копіювати URL'''
download_button = '''Завантажити'''
download_as_button_and_menu = '''Завантажити як…'''
rename_short = '''Переназвати'''
always_download_as_menu = '''Завжди завантажувати як…'''
download_audio_button = '''Аудіо'''
download_audio_and_video_menu = '''Аудіо та відео'''
download_audio_only_menu = '''Тільки аудіо'''
audio_only_for_this_website = '''Завжди тільки аудіо для цього сайту'''
details = '''Детальніше'''
report = '''Повідомити'''
reporting = '''Відправка…'''
reported_thankyou = '''Дякую!'''

[web]
back = '''Назад'''
header_help = '''Допомога'''
header_ask_question = '''Задайте нам питання'''
activate_title = '''Активація'''
activate_pending = '''Очікування…'''
activate_success = '''Успіх'''
activate_error = '''Помилка'''
activate_no_addon_found = '''Розширення не знайдено. Воно встановлене?'''
activate_no_method_found = '''Метод не знайдено.'''
activate_help_me = '''Допоможіть мені.'''
issue_title = '''Відновлення покупки'''
issue_submit = '''Підтвердити'''
issue_thank_you = '''Дякуємо!'''
issue_enter_email = '''Щоб відновити покупку, введіть email, який використовували при купівлі:'''
issue_email_sent = '''Ми надіслали вам лист із посиланням для активації.'''
issue_or_digit = '''Або введіть 6-значний код із листа:'''
issue_just_digit = '''Введіть 6-значний код, який ми вам надіслали:'''
issue_i_have_a_code = '''(Натисніть тут, якщо у вас вже є код)'''
issue_i_have_a_key = '''(Натисніть тут, якщо у вас є ліцензійний ключ)'''
issue_key = '''Введіть ліцензійний ключ Video DownloadHelper:'''
landing_text1 = '''Завантажуйте будь-яке відео з будь-яких сайтів — усе просто!'''
landing_text2 = '''Підтримка 1000+ сайтів'''
landing_text3 = '''Довіряють 7 мільйонів користувачів'''
landing_text4 = '''4.5 зірок у магазині розширень'''
landing_install_for_google = '''Встановити для Chrome'''
landing_install_for_mozilla = '''Встановити для Firefox'''
landing_install_for_microsoft = '''Встановити для Edge'''
landing_feature1_title = '''HD-завантаження на максимальній швидкості'''
landing_feature1_description = '''Завантажуйте відео у високій якості на максимальній швидкості. Ми пишаємося найшвидшим движком завантаження.'''
landing_feature2_title = '''Архівуйте відео'''
landing_feature2_description = '''Зберігайте улюблені відео, щоб нічого не втратити.'''
landing_feature3_title = '''Підтримка live-стримів'''
landing_feature3_description = '''Дивіться трансляції офлайн без обмежень за часом.'''
landing_feature4_title = '''Завантаження аудіо'''
landing_feature4_description = '''Витягайте аудіо з відео у MP3 або подкасти.'''
premium_hero1 = '''Одна оплата — довічне використання'''
premium_hero2 = '''Придбайте ліцензію Video DownloadHelper назавжди.'''
premium_hero3 = '''Завантажуйте відео скільки завгодно без обмежень!'''
premium_supported_payment_methods = '''Підтримувані способи оплати'''
premium_buy = '''купити'''
welcome_text = '''Тепер ви не пропустите жодного відео!'''
welcome_pin_message = '''Закріпіть іконку додатка на панелі інструментів:'''
